name: Build and run

on:
  workflow_dispatch:
    inputs:
      directory:
        required: true
        type: string
        description: Path to tested project
  workflow_call:
    inputs:
      directory:
        required: true
        type: string

jobs:
  build-and-run:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          java-package: 'jdk+fx'

      - name: Install gradle
        uses: gradle/gradle-build-action@v2

      - name: Build and run tests
        run: gradle clean build
